version: '3.8'
services:
  zookeeper:
    image: zookeeper:3.7.0
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sales_db
    ports:
      - "5432:5432"
    networks:
      - app-network

  producer:
    build: ./producer
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: sales
    networks:
      - app-network

  consumer:
    build: ./consumer
    depends_on:
      - kafka
      - db
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: sales
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sales_db
    networks:
      - app-network

  streamlit:
    build: ./streamlit
    ports:
      - "8501:8501"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
